### ISSUE TITLE
Incosistent map generation when using merged laser scan using ira_laser_tools

### ISSUE THREAD

**Issue by maker-ATOM** [ros-perception/slam_gmapping#109]
I have two sources of LiDAR sensor on the robot one in the front and other on the back with 270 field view for both, I am using https://github.com/iralabdisco/ira_laser_tools to merge the two sensors to produce a single 360 field of laser scan data. The `odom => base_link` transform is provide by **GAZEBO**.

Gmapping does produce a map with merged LaserScan data but the map generated is a bit inconsistent, 

![Screenshot from 2024-03-03 17-01-19](https://github.com/ros-perception/slam_gmapping/assets/87944335/7bc71a8e-2659-49cc-ab1b-a386c0cddc7f)

The map generated by any of the front or rear LaserScan sensor is as expected,

![Screenshot from 2024-03-03 17-00-52](https://github.com/ros-perception/slam_gmapping/assets/87944335/ca957fab-8da3-4a7e-aa08-bccfa4f8f753)

Below is the metadata for all the sensor,

Merged:
```
header: 
  seq: 244
  stamp: 
    secs: 158
    nsecs: 274000000
  frame_id: "merge_lidar"
angle_min: -3.1414999961853027
angle_max: 3.1414999961853027
angle_increment: 0.005799999926239252
time_increment: 0.0
scan_time: 0.03333330154418945
range_min: 0.20000000298023224
range_max: 5.0
```

Front:
```
header: 
  seq: 15
  stamp: 
    secs: 134
    nsecs: 513000000
  frame_id: "front_lidar_sensor"
angle_min: -2.3561899662017822
angle_max: 2.3561899662017822
angle_increment: 0.008742820471525192
time_increment: 0.0
scan_time: 0.0
range_min: 0.20000000298023224
range_max: 5.0
```

Rear:
```
header: 
  seq: 565
  stamp: 
    secs: 191
    nsecs: 371000000
  frame_id: "rear_lidar_sensor"
angle_min: 0.7853900194168091
angle_max: 5.497769832611084
angle_increment: 0.008742820471525192
time_increment: 0.0
scan_time: 0.0
range_min: 0.20000000298023224
range_max: 5.0
```

What could be the reason which leads to such an inconsistent map generation using merged LaserScan data?
